### PR TITLE
Composer.json, modman and update README file

### PR DESCRIPTION
**Pull request by giuseppemorelli**
Added composer.json file
Added modman file
Updated README file with the instructions 

Remember you have to add tag 1.2.5 at this time to use composer correctly. Otherwise the composer give you an error that it can't find the right version (release)

### CODE REVIEW

**Comment by midimarcus** [comment]
I suppose you mean a git tag. For future tags changes to composer.json are needed?

**Comment by giuseppemorelli** [comment]
Yes, git tag. 
Composer.json (for repository) doesn't need changes for future changes (or tags). Its used only for project as "repository configuration".

Here an example of composer.json for project:

{
    "require": {
        "magento-hackathon/magento-composer-installer": "*",
        "magespecialist/msp_cashondelivery"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        
        {
            "type": "vcs",
            "url": "git@github.com:magespecialist/MSP_CashOnDelivery.git"
        }

    ],
    "extra":{
        "magento-root-dir":"./",
        "magento-deploystrategy":"copy",
        "magento-force": true
    }
}



ADDITIONAL INFORMATIONS
- the composer.json for project is placed in the root project   ("magento-root-dir":"./",)
- deploy strategy => copy ("magento-deploystrategy":"copy",)    Copy the source from vendor folder to magento root dir (use modman file automatically)
- overwrite files if the extension exists  ("magento-force": true)

**Comment by midimarcus** [comment]
OK, we'll merge this commit asap, but we'll not include files in tgz or zip packages.
Thanks.

**Comment by giuseppemorelli** [comment]
You don't need to include tgz or zip packages.
Advice: to have a complete composer file with dependency you have to create magespecialist/msp_common repository and add it into composer.json of magespecialist/msp_cashondelivery requirement section

When you create the msp_common repository I can create all the composer file needed. :+1:

**Comment by midimarcus** [comment]
I mean packages for Connect and for our website showcase.
MSP_Common github repo is on the way, I'll notify you when available.
TNX

**Comment by midimarcus** [comment]
Here is MSP_Common. Since it's not merged yet, can I close this pull request and wait for another one with composer file updated?

**Comment by giuseppemorelli** [comment]
Yes, close this pull request.
I'll open a new pull request with files updated.

**Pull request closed without merging**
